@baseUrl = http://localhost:3001
@userId = 69abcf126a23db22a37e4cea
@tokenaccess = 
@tokenrefresh = 
### USER API-----------------------------------------------------------------


### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "test1",
  "email": "test1@example.com",
  "password": "test1"
}

### Get all users
GET {{baseUrl}}/users
Cookie: accessToken={{tokenaccess}}; refreshToken={{tokenrefresh}}

### Get a user by id
GET {{baseUrl}}/users/{{userId}}
Cookie: accessToken={{tokenaccess}}
### Update a user by id
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

{
  "role": "admin"
}

### Delete a user by id
DELETE {{baseUrl}}/users/{{userId}}
Cookie: accessToken={{tokenaccess}}



### AUTH API-----------------------------------------------------------------



### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "testing1",
  "email": "tophits2031@gmail.com",
  "password": "passwordtest2",
  "phone": "9876543211",
  "role": "user"
}

### Verify email for a user
POST {{baseUrl}}/auth/verify-email
Content-Type: application/json

{
  "email": "appmyfirst67@gmail.com",
  "otp": "228478"
}


### Resend OTP for email verification
POST {{baseUrl}}/auth/resend-otp
Content-Type: application/json

{
  "email": "appmyfirst67@gmail.com"
}

### Forgot password for a user
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "bikrammodi132@gmail.com"
}

### verify OTP for password reset
POST {{baseUrl}}/auth/verify-reset-otp
Content-Type: application/json

{
  "email": "bikrammodi132@gmail.com",
  "otp": "287878"
}


### Reset password for a user
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
    "resetToken":"6d84a7f33fd5c3a6c5fc995f722b2af89a41b9ab1148762b77024c905b2fd7b4",
    "password":"NewPassword123",
    "confirmPassword":"NewPassword123"
}

### Login a user
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "bikrammodi132@gmail.com",
  "password": "NewPassword123"
}

### Logout a user
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

### Refresh access token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}; refreshToken={{tokenrefresh}}

### Get current user profile
GET {{baseUrl}}/auth/me
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}; refreshToken={{tokenrefresh}}






###############################################################
# AI Module
# Base URL
###############################################################


###############################################################
# Health Check
###############################################################

GET {{baseUrl}}/ai/health
Accept: application/json

###

###############################################################
# List Installed Ollama Models
###############################################################

GET {{baseUrl}}/ai/models
Accept: application/json

###

###############################################################
# Gemma 3 1B
###############################################################

POST {{baseUrl}}/ai/chat
Content-Type: application/json

{
    "model": "gemma3:1b",
    "prompt": "Introduce yourself in one paragraph."
}

### Generate AI Response

POST {{baseUrl}}/ai/chat/gen-ai
Content-Type: application/json

{
    "message": "Explain RAG"
    
}

### Generate RAG Response

POST {{baseUrl}}/ai/chat/rag-ai
Content-Type: application/json

{
    "message": "Explain Bikram projects?"
    
}

### Generate Agentic Response
POST {{baseUrl}}/ai/chat/agentic-ai
Content-Type: application/json

{
    "message": "calculate 3+6"
    
}



### Upload Document
POST {{baseUrl}}/documents/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="w3.pdf"
Content-Type: application/pdf

< ./src/test-data/w3.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--






















###############################################################
# Phi-3
###############################################################

POST {{baseUrl}}/ai/chat
Content-Type: application/json

{
    "model": "phi3:latest",
    "prompt": "Explain what React Context API is."
}

###

###############################################################
# Qwen 2.5 Coder
###############################################################

POST {{baseUrl}}/ai/chat
Content-Type: application/json

{
    "model": "qwen2.5-coder:1.5b",
    "prompt": "Write a Node.js Express hello world server."
}

###

###############################################################
# JavaScript Question
###############################################################

POST {{baseUrl}}/chat
Content-Type: application/json

{
    "model": "qwen2.5-coder:1.5b",
    "prompt": "Explain closures in JavaScript."
}

###

###############################################################
# React Question
###############################################################

POST {{baseUrl}}/chat
Content-Type: application/json

{
    "model": "gemma3:1b",
    "prompt": "What are React Hooks?"
}

###

###############################################################
# Node.js Question
###############################################################

POST {{baseUrl}}/chat
Content-Type: application/json

{
    "model": "phi3:latest",
    "prompt": "Explain middleware in Express."
}

###

###############################################################
# MongoDB Question
###############################################################

POST {{baseUrl}}/chat
Content-Type: application/json

{
    "model": "gemma3:1b",
    "prompt": "Explain MongoDB Aggregation Pipeline."
}

###

###############################################################
# Docker Question
###############################################################

POST {{baseUrl}}/chat
Content-Type: application/json

{
    "model": "qwen2.5-coder:1.5b",
    "prompt": "Explain Docker Compose."
}

###

###############################################################
# AI Test
###############################################################

POST {{baseUrl}}/ai/chat
Content-Type: application/json

{
    "model": "gemma3:1b",
    "prompt": "What is Artificial Intelligence?"
}

###

###############################################################
# Custom Prompt Template
###############################################################

POST {{baseUrl}}/ai/chat
Content-Type: application/json

{
    "model": "phi3:latest",
    "prompt": "YOUR CUSTOM PROMPT HERE"
}











### USER PREFERENCE API-----------------------------------------------------------------

### Get user preferences
GET {{baseUrl}}/preferences/get
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

### Update user preferences
PATCH {{baseUrl}}/preferences/update
Content-Type: application/json
Cookie: accessToken={{{{tokenaccess}}}}

{
  "defaultModel": "gpt-3.5-turbo",
  "temperature": "0.7",
  "theme": "light"
}




### CONVERSATION API-----------------------------------------------------------------

@convId=69aad2036a23db22a37e2f67

### Create a new conversation
POST {{baseUrl}}/conversations
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

{
  "title": "My Third Conversation",
  "model": "gpt-3.5-turbo",
  "systemPrompt": "You are a helpful assistant.",
  "visibility": "private",
  "isArchived": "false"
}


### Create a new conversation for guest user
POST {{baseUrl}}/conversations/guest
Content-Type: application/json

{
  "title": "My fourth Conversation",
  "model": "gpt-3.5-turbo",
  "systemPrompt": "You are a helpful assistant.",
  "visibility": "private",
  "isArchived": "false"
}


### Get all conversations for the authenticated user
GET {{baseUrl}}/conversations
Cookie: accessToken={{tokenaccess}}



### Get a single conversation by ID
GET {{baseUrl}}/conversations/{{convId}}
Cookie: accessToken={{tokenaccess}}

### Update a conversation by ID
PATCH {{baseUrl}}/conversations/{{convId}}
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

{
  "title": "Updated first Conversation Title",
  "model": "gpt-4",
  "systemPrompt": "You are an updated helpful assistant.",
  "visibility": "shared",
  "isArchived": "false"
}

### Delete a conversation by ID
DELETE {{baseUrl}}/conversations/{{convId}}
Cookie: accessToken={{tokenaccess}}





### MESSAGE API-----------------------------------------------------------------

@messageId=69aad22e6a23db22a37e2fbb
### Add a message to a conversation
POST {{baseUrl}}/messages/conversations/{{convId}}/messages
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

{
  "content": "testing make it simple "
}


### Add a message to a conversation by guest user for free
POST {{baseUrl}}/messages/conversations/{{convId}}/messages/guest
Content-Type: application/json

{
  "content": "explain in detail"
}

### Get all messages in a conversation
GET {{baseUrl}}/messages/conversations/{{convId}}/messages
Cookie: accessToken={{tokenaccess}}

### Update a message in a conversation
PATCH {{baseUrl}}/messages/messages/{{messageId}}
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

{
  "content": "can you write mern code?"
}

### Regenerate an assistant message in a conversation
POST {{baseUrl}}/messages/messages/{{messageId}}/regenerate
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

{
  "conversationId": "{{convId}}"
}




### MESSAGE VERSION API-----------------------------------------------------------------

@messageVersionId=69aad22e6a23db22a37e2fbb
@conversationId=69aad2036a23db22a37e2f67

### Get all versions of a message
GET {{baseUrl}}/messagesvr/{{conversationId}}/{{messageVersionId}}/versions



### CONTENT FLAG API-----------------------------------------------------------------

@flagId=6998327f5ecb1b98a950e86c



### Flag a message for review automatic system generated
POST {{baseUrl}}/flags
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

{
  "messageId": "{{messageId}}",
  "category": "hate",
  "severity": "high"
}



### Get all flagged messages (Admin only)
GET {{baseUrl}}/flags
Cookie: accessToken={{tokenaccess}}

### Update the action taken on a flagged message (Admin only)
PATCH {{baseUrl}}/flags/{{flagId}}
Content-Type: application/json
Cookie: accessToken={{tokenaccess}}

{
  "actionTaken": "blocked"
}






### USAGE METRIC API-----------------------------------------------------------------

### Get usage metrics for the authenticated user
GET {{baseUrl}}/metrics/usage
Cookie: accessToken={{tokenaccess}}

### Get usage metrics for all users (Admin only)
GET {{baseUrl}}/metrics/usage/all
Cookie: accessToken={{tokenaccess}}









### ---------------------------THE END-----------------------------------------------------------------